### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by My1**
fixed links that refer to specific issue threads in old repo

### CODE REVIEW

**Review by 4s3ti — APPROVED** [review]
LGTM! 

Thank you.

**Comment by 4s3ti** [comment]
just a note, in the future please make sure to follow the commit style as per https://github.com/streamdeck-linux-gui/streamdeck-linux-gui#general-guidelines

> When writing your commit messages, please follow the [Angular commit message](https://gist.github.com/brianclements/841ea7bffdb01346392c).

**Comment by My1** [comment]
okay I just made in in Github web, I am not even sure how to adapt everything to there but sure next time I'll just make an issue

**Comment by 4s3ti** [comment]
for this kind of cases is sort of fine as i can change the header. for more complex stuff it gets tricky

**Pull request merged**
