### PR TITLE
build: bump dependencies -- python 3.12, streamdeck 0.9.5

### PR DESCRIPTION
**Pull request by ajbucci**
Bumping dependencies to address the failing Fedora builds #137 and add basic initial support for the stream deck plus

### CODE REVIEW

**Comment by 4s3ti** [comment]
LGTM ... @rkmax any takes?

**Comment by rkmax** [comment]
I think we need to include python 3.12 in the test matrix. and of course solve the conflicts there

i have no clear idea how the streamdeck+ will work, since currently we implement only buttons, I know the plus include dials and other display formats than the squared buttons but I think if nothing gets broken it's OK to bump the dependency

I'll test this breach locally today later and give feedback

**Comment by ajbucci** [comment]
This is just the first step towards getting the Plus working. With the dependency bump the 8 regular buttons do load into the UI and function as intended, and I have not found any regressions with the updated dependency. The touchscreen/dials won't work until we add code to interface with that part of the upstream lib, and then add corresponding widgets to the GUI.

**Comment by rkmax** [comment]
> With the dependency bump the 8 regular buttons on the Plus do load into the UI and function as intended, and I have not found any regressions with the updated dependency -- but we should do more testing to make certain there are no regressions. The touchscreen/dials won't work until we add code to interface with that part of the upstream lib, and then add corresponding widgets to the GUI.

Good to know. then just fix the conflicts and ensure to include `3.12` [here](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/blob/main/.github/workflows/test.yaml#L25)

**Comment by ajbucci** [comment]
Thanks @rkmax ! should be all set

**Comment by 4s3ti** [comment]
will trigger the release workflow during the weekend :)

**Pull request merged**
