### PR TITLE
feat: replace pynput by evdev

### PR DESCRIPTION
**Pull request by rkmax**
## Description of the changes
The `pynput` library is not well-supported by Wayland; therefore, it has been replaced with `evdev`, which appears to be a more robust option.

The `keys` field has been substituted by a text editor featuring real-time autocomplete functionality, as opposed to a fixed list.

In the event that an invalid key name is entered, a warning will be displayed in the system tray.

# Demo

https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/assets/395707/322371cb-356b-4b6b-8b7c-60303febb0de

### CODE REVIEW

**Comment by 4s3ti** [comment]
check the conflicts when you can please, most likely cause by merging the previous PR.

**Comment by Data-007** [comment]
@rkmax Something on Arch requiring tkinter or python-tk unsure. Think x11
See image below. More on discord.
image

**Comment by 4s3ti** [comment]
This is a really HUGE change, not sure how to go about it, but I somewhat agree with as wayland starts to become the de-facto protocol.

I believe this might be a problem with installing the dependency. But well, gotta start somewhere. 

For now, running with poetry from your branch: 

```
**$poetry run streamdeck
Traceback (most recent call last):
  File "/home/f0rs3ti/.cache/pypoetry/virtualenvs/streamdeck-linux-gui-j3PZ8RXd-py3.11/lib/python3.11/site-packages/Xlib/xauth.py", line 43, in __init__
    raw = open(filename, 'rb').read()
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/f0rs3ti/.Xauthority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/f0rs3ti/temp/streamdeck-ui/streamdeck_ui/gui.py", line 46, in <module>
    from streamdeck_ui.modules.keyboard import KeyPressAutoComplete, keyboard_press_keys, keyboard_write
  File "/home/f0rs3ti/temp/streamdeck-ui/streamdeck_ui/modules/keyboard.py", line 3, in <module>
    import pyautogui
  File "/home/f0rs3ti/.cache/pypoetry/virtualenvs/streamdeck-linux-gui-j3PZ8RXd-py3.11/lib/python3.11/site-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/home/f0rs3ti/.cache/pypoetry/virtualenvs/streamdeck-linux-gui-j3PZ8RXd-py3.11/lib/python3.11/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/f0rs3ti/.cache/pypoetry/virtualenvs/streamdeck-linux-gui-j3PZ8RXd-py3.11/lib/python3.11/site-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/f0rs3ti/.cache/pypoetry/virtualenvs/streamdeck-linux-gui-j3PZ8RXd-py3.11/lib/python3.11/site-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/home/f0rs3ti/.cache/pypoetry/virtualenvs/streamdeck-linux-gui-j3PZ8RXd-py3.11/lib/python3.11/site-packages/Xlib/protocol/display.py", line 60, in __init__
    auth_name, auth_data = connect.get_auth(self.socket,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/f0rs3ti/.cache/pypoetry/virtualenvs/streamdeck-linux-gui-j3PZ8RXd-py3.11/lib/python3.11/site-packages/Xlib/support/connect.py", line 91, in get_auth
    return mod.get_auth(sock, dname, host, dno)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/f0rs3ti/.cache/pypoetry/virtualenvs/streamdeck-linux-gui-j3PZ8RXd-py3.11/lib/python3.11/site-packages/Xlib/support/unix_connect.py", line 103, in new_get_auth
    au = xauth.Xauthority()
         ^^^^^^^^^^^^^^^^^^
  File "/home/f0rs3ti/.cache/pypoetry/virtualenvs/streamdeck-linux-gui-j3PZ8RXd-py3.11/lib/python3.11/site-packages/Xlib/xauth.py", line 45, in __init__
    raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 2] No such file or directory: '/home/f0rs3ti/.Xauthority'
**
```

I don't have Xauthority at all because I don't use X at all and have no need to have any settings there. Dependency on this file should be removed.

**Comment by rkmax** [comment]
@4s3ti I just retaking this. I cleanup the history. I give up for now regarding the wayland support. I did different experiments even writenn modules in C but when test on different version sometimes fails

let me know if you can merge this one

**Comment by 4s3ti** [comment]
I am okay with merging this, but I am not so sure what is the best way to handle this ... this feels more backwards incompatible change :thinking:  maybe should be marked as "BREAKING CHANGE" and made a major release?

**Comment by ajbucci** [comment]
> I am okay with merging this, but I am not so sure what is the best way to handle this ... this feels more backwards incompatible change 🤔 maybe should be marked as "BREAKING CHANGE" and made a major release?

Does this break anything? At a glance, it looks like there is code to handle the old pynput keypress value mappings, so I don't think there are any breaking changes with respect to the config json.

**Comment by rkmax** [comment]
thanks @ajbucci for pointing a solution for wayland. I really appreciate.

@4s3ti regarding if is a breaking change. I dont think so... no functionality were touched more than the dependencies

but leave the PR open since I'll fixes mentioned by @ajbucci to see if that works correctly on ubuntu 22/23 as well like if I need to add addtiional checks/steps in the installations instructions

**Comment by 4s3ti** [comment]
alright .. looks good to me then ... let me know when its okay to be merged then ... or .. rather ,, I think you now have the permissions for it as well @rkmax

**Comment by ajbucci** [comment]
I cleaned up the implementation here: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/commit/93d206c82d84db3d4db70718aaa22a97bc65e398

**Comment by rkmax** [comment]
I just include the logic to exclude the bad ecodes and include the permissions docs and scripts for installations

**Comment by 4s3ti** [comment]
lgtm @rkmax is this ready for being merged?

**Comment by rkmax** [comment]
> lgtm @rkmax is this ready for being merged?

yeah, I think is ready

**Pull request merged**
