### PR TITLE
fix: Shut down the CLI server on SIGTERM

### LINKED ISSUE #122: [BUG]: Streamdeck slowing down shutdowns / reboots
### In raising this issue I confirm that

- [X] I have fully completed the issue template
- [X] I have searched open and closed issues for duplicates
- [X] I have read the [Contribution Guidelines](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/contributing-guide/)
- [X] I have read the [Code of Conduct](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/contributing/code-of-conduct/)
- [X] I have read the [Documentation](https://streamdeck-linux-gui.github.io/streamdeck-linux-gui/)

### Describe the bug

Hello, this app costantly slows down my reboots, i have to wait 45 seconds

### Steps to reproduce the behavior

Just reboot with the app  open

### Expected behavior

Reboot without issues

### Screenshots

IMG_7486

### System Information

- Fedora 39
- Gnome

### Stream Deck Version

Stream Deck MK.2

### PR DESCRIPTION
**Pull request by rdnelson**
When systemd requested a shutdown via SIGTERM, the CLI server was left running. That thread prevented the shutdown of the app until another SIGTERM/SIGINT/SIGKILL was received. By shutting down the CLI server on the first signal, the app exits gracefully.

Fixes #122

### CODE REVIEW

**Comment by rdnelson** [comment]
I wasn't sure if there would be any documentation or tests that are appropriate for a fix like this given its relatively simple nature. I'm happy to add anything that would be useful though.

The check above also appears to be failing on a vulnerability scan, but with this PR not changing any dependencies, it feels like it's probably out of scope for this change.

**Comment by rdnelson** [comment]
Thanks! I ran the `lint.sh --fix` script and it didn't come back with any changes, were there any you were expecting to see?

**Comment by rdnelson** [comment]
Though I should say that the lint script did report the same vulnerabilities in `pillow` and `urllib3` that the check failed on. Not sure what the best approach to addressing that is, because it feels wholly unrelated to this specific change.

**Comment by 4s3ti** [comment]
Please rebase and force push tests should be able to run now.

**Comment by rdnelson** [comment]
Pushed the rebase, and retargetted against main. I must have seen an older version of the contribution guide when I targeted the  `develop` branch.

**Pull request merged**
