### PR TITLE
Operating StreamDeck from a terminal

### PR DESCRIPTION
**Pull request by asuka1975**
Hi, thank you for keeping the project alive!

I am submitting a Pull Request to add a new feature to your project. This feature allows for controlling a StreamDeck through the terminal.

This PR provides the following functions:
- transition pages
- change button brightness
- change button text
- change button text alignment
- changing the command associated with a button
- change text input associated with button
- change key input associated with button
- change button icon
- clear button icon
These functions can be used by running the command streamdeckc with specific arguments. For example, the command streamdeckc --page 1 will navigate to the second page of the StreamDeck-UI.

To send commands to the StreamDeck-UI, the feature uses a Unix domain socket located at /tmp/streamdeck-ui.sock. I have tested the code and it appears to be working correctly.

While I believe they will be beneficial to users, I understand that any changes to a project's codebase can be cause for concern. If there are any concerns you have regarding the changes I have made, please let me know and I would be happy to discuss them with you. I am committed to ensuring that the changes I have made are in the best interest of the project and its users.

I would be grateful for your review.

### CODE REVIEW

**Comment by 4s3ti** [comment]
HI, thanks a lot for the pull request. 

Please fix the linting to get it according to the project standard. 
you can test it locally with the `scripts/lint.sh` script. you can also run the tests yourself with the `scripts/test.sh` script. 

since this is a quite big new feature, would be nice to have some unit tests accompanying it to at least help identifying breaking changes on the code later on. 

Other than that it generally looks good and i would be glad to approve it.

**Comment by asuka1975** [comment]
Thank you very much for your review!
I have improved the source code according to the messages in linter.sh and implemented unit tests for the commands.

**Comment by 4s3ti** [comment]
Linter still complaining :( 

```
Run ./scripts/lint.sh
+ poetry run mypy --ignore-missing-imports streamdeck_ui/ --exclude 'ui_main.py|resources_rc.py|ui_settings.py'
streamdeck_ui/cli/server.py:123: error: invalid syntax  [syntax]
Found 1 error in 1 file (errors prevented further checking)
Error: Process completed with exit code 2.
```

**Comment by asuka1975** [comment]
Oh, sorry.
It seems I hadn't managed to remove the new syntax for Python completely.
I hope that's OK now.

**Comment by 4s3ti** [comment]
oooh wait!  now you made me realize ... then maybe something is wrong with the tests, I'd expect the tests to be running with a more recent version of python :thinking:

Might have to figure that one out. 

are you running the `scripts/lint.sh` script locally ?

**Comment by asuka1975** [comment]
Yes, running that locally works perfectly fine. However, this environment is using python 3.10, which might be different from the python version in the CI container.

**Comment by 4s3ti** [comment]
ci container seems to be using v3.11 

```

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python     
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
``` 

but I suspect something else is making stuff run with another python version.

**Comment by asuka1975** [comment]
Hmm... It appears that Python 3.11 is being correctly installed during the setup.

```
Run actions/setup-python@v4
  with:
    python-version: 3.11
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
Installed versions
  Successfully set up CPython (3.11.4)
 ```

**Comment by 4s3ti** [comment]
ok... I'll merge and try to figure our what's wrong from my side.

**Comment by asuka1975** [comment]
Thank you! I'm sorry for any inconvenience caused.

**Comment by 4s3ti** [comment]
no worries, I guess this is the kind of things to expect when a project is stale for so long and no one is around to explain how they used to work. now there's a bit of work to figure things out and get it working.

If you hate the time and the will, would you mind to add the new feature stuff into the `docs/`  ??

**Comment by 4s3ti** [comment]
yeah ... fixed it: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/commit/7a9743212211e429184944d51bc0a010da2878f8

bumping version on pyproject.toml, and generating a new poetry.lock does the trick.

**Comment by 4s3ti** [comment]
alsso I seem to be getting this error when running locally: 

```
$poetry run streamdeck
Exception in thread Thread-2 (_run):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/f0rs3ti/Devel/streamdeck-linux-gui/streamdeck_ui/cli/server.py", line 67, in _run
    self.sock.bind(path)
OSError: [Errno 98] Address already in use
```

maybe worth to catch this properly? what could be causing it?

**Comment by asuka1975** [comment]
I suspect that the problem arises because the /tmp/streamdeck_ui.sock, used for communication with the terminal, hasn't been cleared since the previous run. I believe we can resolve this by checking for its existence during the setup and deleting it if it's present. This action should eliminate any impact on functionality. I'm currently in the process of creating a commit to address this issue.

**Pull request merged**
