### PR TITLE
fix: prefer fallback fonts over system fonts

### PR DESCRIPTION
**Pull request by ajbucci**
In the case where the user already has the DEFAULT_FONT installed if the file name differs from DEFAULT_FONT then find_font_info will result in an infinite loop. #118

### CODE REVIEW

**Comment by rkmax** [comment]
ensure to run `scripts/lint.sh --fix`

**Comment by ajbucci** [comment]
It passes linting. It's failing on safety w/ pillow < 10. Should I add to ignore?

**Comment by 4s3ti** [comment]
Please rebase.

**Comment by 4s3ti** [comment]
Please address the errors in the tests.

**Comment by ajbucci** [comment]
> Please address the errors in the tests.

The fonts module was previously copied to streamdeck-ui/modules/fonts.py. I was cleaning up the unused files @ streamdeck-ui/fonts.py and the corresponding tests. tests/modules/test_fonts.py is passing.

**Comment by ajbucci** [comment]
> Please address the errors in the tests.

All set. I added some additional tests to catch errors with different system font configurations.

**Pull request merged**
