### PR TITLE
Add support for Font configuration

### PR DESCRIPTION
**Pull request by rkmax**
Functionality to customize the fonts

## Description of the changes

Add a more complete configuration of the text displayed by the applications

- Allow change Horizontal Alignment
- Allow change font size
- Allow changes in the font color

## Demo
image

### CODE REVIEW

**Comment by rkmax** [comment]
pending to fix the conflicts

**Comment by rkmax** [comment]
please ensure to enable the option of squash commits before merge

**Comment by 4s3ti** [comment]
Please run locally the `scripts/test.sh` and check the errors, please make sure they pass.

**Comment by 4s3ti** [comment]
All looks good to me so far. how do you feel about trying to at least keep the test code coverage? would you be able to update the tests to cover the feature?

There's no wright or wrong answer here, It will still make it, however i would like to have some tests to rely on when looking at pull requests.

**Comment by 4s3ti** [comment]
The issues with the linting are probably solved now, please rebase your branch. to get the latest `develop`

**Comment by rkmax** [comment]
I'll take a look at the smart automated test to increase the coverage an rebase agaist develop

**Comment by 4s3ti** [comment]
Thank you. 
Merged even tho coverage went down.

if you have the time and want to do so would be cool to get some more tests in a separate PR, otherwise its all good.

**Comment by rkmax** [comment]
> Thank you. Merged even tho coverage went down.
> 
> if you have the time and want to do so would be cool to get some more tests in a separate PR, otherwise its all good.

yeah, I was not used to the automatic test and noticed that we need to write specific manual test, sadly my free time dropped to almost nothing.

I'm trying to invest my spare time into the plugin stuff, but probably other refactors will be needed before that like decoupling some parts of api.py

**Pull request merged**
