### PR TITLE
Plugin support (with Home Assistant)

### PR DESCRIPTION
**Pull request by gensyn**
A couple of weeks ago I created a pull request to merge my branch which added support for controlling Home Assistant. It was suggested that this should not be a core feature of streamdeck-linux-gui but would be a useful plugin. At this time, there was no plugin support present so I played around with it myself. Only now do I realize there is already a pull request by @G4PLS for plugin support. But since that PR has been stale for almost two months I thought I would put my ideas up for discussion.

My design is heavily influenced by the needs of my [plugin for Home Assistant](https://github.com/gensyn/home-assistant) so it is probably not fully fletched but should be a good starting point.

Main window

My implementation loads all plugins from the plugins folder (if you want to try it out, you can clone or copy my repository mentioned above to the folder) and lists them in the new menu item "Plugins". If a plugin provides a layout for plugin settings (in contrast to button settings), it can be accessed via this menu:

plugin_settings

A button can now also have settings for each plugin - just select a plugin from the Combobox and click the gear button to enter them.

plugin_button_settings

This is different from the other plugin PR where only one plugin could be selected per button. It's probably a minor use case to configure multiple plugins for one button, but it might be nice to have.

My main issue were the UI files. Generated code is usually terrible and this is no exception. I cannot fathom why anyone would want to generate these files - I find it much easier to edit them manually, which is what I did. This is also why I don't expect this PR to be merged as is, but I'm putting it out there to get some feedback and get a discussion going.

Thanks.

### CODE REVIEW

**Comment by 4s3ti** [comment]
hi @gensyn  I really appreciate your tremendous effort with this!!! 

However a new player showed up in town: [StreamController](https://github.com/StreamController/StreamController) I have been talking with the main developer and we are actually considering joining forces, and focus our effort into that one. It was build from ground up, has plugin implementation in mind and seems to have a more modern software development approach. 

Maybe your time would be better spent adding your plugin there. what you say?

**Comment by gensyn** [comment]
> hi @gensyn I really appreciate your tremendous effort with this!!!
> 
> However a new player showed up in town: [StreamController](https://github.com/StreamController/StreamController) I have been talking with the main developer and we are actually considering joining forces, and focus our effort into that one. It was build from ground up, has plugin implementation in mind and seems to have a more modern software development approach.
> 
> Maybe your time would be better spent adding your plugin there. what you say?

If you think the other repository is gonna take over then I'm gonna give it a try.

**Comment by 4s3ti** [comment]
yes, we have started already testing and working on it, and its indeed a much better solution than this one. and I have already created a [discussion/feature request](https://github.com/StreamController/StreamController/discussions/36). 

Also good thing is that you can host the plugin on your own GitHub account instead of submitting it into the repository and have it completely independent from the main application :)

**Comment by Core447** [comment]
> If you think the other repository is gonna take over then I'm gonna give it a try.

Hey, If you need help you can join the [StreamController Discord](https://discord.gg/MSyHM8TN3u).

**Comment by gensyn** [comment]
> Hey, If you need help you can join the [StreamController Discord](https://discord.gg/MSyHM8TN3u).

Thanks, I will try that. I can't get StreamController to work. It keeps insisting that the Xdp namespace is not present, even though all necessary packages should be installed. Maybe someone on Discord had that problem before me.

**Comment by Core447** [comment]
> It keeps insisting that the Xdp namespace is not present, even though all necessary packages should be installed

You can find the installation instructions [here](https://streamcontroller.github.io/docs/latest/installation/#github). Probably one of the following packages is missing on your system: `xdg-desktop-portal xdg-desktop-portal-gtk libportal libportal-gtk4`.

**Pull request closed without merging**
