### PR TITLE
fix: add support for emoji

### PR DESCRIPTION
**Pull request by inkhey**
Just a proposal in order to support emoji for text.
Unfortunately, this require for now to use a non-upstream version of pilmoji.

### CODE REVIEW

**Comment by inkhey** [comment]
@enterFaisal do you expect to propose your patch for pilmoji as upstream ?

**Comment by 4s3ti** [comment]
not really in favor of adding extra dependencies, this one being a non upstream version of it I am even less inclined about it. if the changes make it to the upstream version then maybe ill be okay with it.

**Comment by rkmax** [comment]
Sounds interesting.

I believe it's important to add tests (even if done manually) to confirm that both the vertical and horizontal alignment, as well as the text shadow that enhances visibility, remain intact. Make sure to be comprehensive. and include in the PR description images showing each case

**Comment by enterFaisal** [comment]
> @enterFaisal do you expect to propose your patch for pilmoji as upstream ?

I don't know how git works,
so do you me to make pull request?

**Comment by rkmax** [comment]
checking pilmoji uses pillow but pillow 10 include some breaking changes that that maybe need to fix it in pilmoji before use it in the project

**Comment by coolapso** [comment]
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/discussions/203

**Pull request closed without merging**
