### PR TITLE
Updated install guide and rename ubuntu.md to debian.md

### PR DESCRIPTION
**Pull request by Narcodepsy**
Install guide updated to allow install to work.

Change from using pip to building within Poetry environment and pulling from github.

### CODE REVIEW

**Review by 4s3ti — CHANGES_REQUESTED** [review]
This does not sound accurate,

I don't have a Debian box to test now, but the steps are almost universal on the installation part. 

when you install an aplication you want it to be available system-wide, therefore the steps you represent don't sound exactly correct. 

Poetry is only creating a virtual env and making sure you have the deps for developing.
doing poetry run, runs the application only there does not install it on the system. 

Poetry should not be needed to install the application or to run it. 

Installation from source on the system should be something like:

`sudo python -m installer dist/*wheel` 

the command above should  add the streamdeck executable in /usr/bin 

or something similar.

**Comment by Narcodepsy** [comment]
It allows the streamdeck to work fully as intended.
Would just require a systemd to start on boot up if desired.

If you try and install through pip system wide it will not allow you on
debian, and prompt you to do it in a virtual environment.

It's a working install guide that allows it to be installed and fully
functional, unlike the current/previous guide.

**Comment by 4s3ti** [comment]
In that case use pipx instead of pip. 

I am not saying it doesn't work. 

what I say is that it does not sound a good way to install applications, just adds more complexity when it should be the other way around. 


I am adding the proper steps to install from source, you can piggy back on them later if you want.

**Comment by 4s3ti** [comment]
actually I believe your steps are really well suited for the contributing guide, there is for sure where they shine because you can test the application and your changes easily without having to build or install!

**Review by sftim — COMMENTED** [review]
`pip` is easy to use. Why should we switch?

**Comment by 4s3ti** [comment]
> `pip` is easy to use. Why should we switch?

There is no reason ,and the suggested solution is not a correct way to install packages. 
It should be either via pip, pipx or via distro package manager, or if one wants from source using the appropriate steps. 

the steps suggested are better suited for running the application when developing and one wants to test and verify while working on it. 

@Narcodepsy  you are welcome to adjust the [contributing guide](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/blob/main/docs/contributing/contributing-guide.md) with those steps if you want.

**Comment by Narcodepsy** [comment]
The pip isn't updated yet for the new fork, so pulls the old fork which
also has issues.

Also the pip machine level install on debian gives errors/advisories to do
in a virtual environment.

No reason why when first point is rectified can't look at changing again
but, having a working guide people can use has more value than a one that
worked and might work again but currently doesn't.

**Comment by 4s3ti** [comment]
There is a pip package: https://pypi.org/project/streamdeck-linux-gui/

As I mentioned, the Virtual env regarding pip is solved with pipx not with poetry which is a development and dependency management tool, not a package manager. 

A working guide doesn't necessarily mean that is the correct guide.

**Pull request closed without merging**
